services:
  django:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/my-user/app
      - external-storage:/media/uploads
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: postgres:15.8-alpine3.20
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB_1:-mydb}
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:1.19.10-alpine
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - external-storage:/media/uploads

volumes:
  external-storage:
    external: true
