# Generated by Django 5.1.2 on 2024-10-27 12:46

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to=videos.models.random_filename, verbose_name='Thumbnail'),
        ),
    ]
