services:
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=${DEBUG:-true}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-converter}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE:-disable}
      # RabbitMQ
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
      - CONVERSION_EXCHANGE=${CONVERSION_EXCHANGE:-conversion_exchange}
      - CONVERSION_QUEUE=${CONVERSION_QUEUE:-video_conversion_queue}
      - CONVERSION_KEY=${CONVERSION_KEY:-conversion}
      - CONFIRMATION_KEY=${CONFIRMATION_KEY:-finish-conversion}
      - CONFIRMATION_QUEUE=${CONFIRMATION_QUEUE:-finish_conversion_queue}
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true

  postgres:
    image: postgres:15.8-alpine3.20
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-converter}
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@user.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-password}
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}

volumes:
  external-storage:
    external: true
